source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target 'PsychicLoan' do

pod 'IQKeyboardManager'

pod 'ChameleonFramework'
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'AFNetworking', '~> 3.0'
#pod 'HYBUnicodeReadable' //将字符转中文
pod 'MMDrawerController', '~> 0.5.7'

pod 'SDWebImage'

pod "AsyncDisplayKit", ’1.9.5’

pod 'DZNEmptyDataSet'#空白填充指引页

pod 'pop', '~> 1.0'
#pod 'MLeaksFinder'

pod 'YYModel'

pod 'ReactiveCocoa'#支持FRP(函数响应式编程)的框架

#蒲公英开放平台
#pod 'Pgyer'
#pod 'PgyUpdate'

#友盟统计开放平台
pod 'UMengAnalytics'#标准SDK，含IDFA

#高德API开放平台
#pod 'AMapLocation'
#pod 'AMapSearch'
#pod 'AMapNavi' #已包含3D地图，无需单独引入3D地图

#个推开放平台
pod 'GTSDK'#标准SDK，含IDFA

end

#target 'NotificationService' do
#platform :ios, "10.0"
#pod 'GTExtensionSDK'
#
#end